apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: godel-system
  labels:
    component: scheduler
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
