apiVersion: v1
kind: Pod
metadata:
  name: back-pod
  labels:
    app: back-pod
  annotations:
    godel.bytedance.com/pod-resource-type: guaranteed
    godel.bytedance.com/pod-launcher: kubelet
    godel.bytedance.com/reservation-index: "reservation-pod"
spec:
  schedulerName: godel-scheduler
  containers:
    - name: back-pod
      image: nginx
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: "1"
          memory: "100Mi"
  restartPolicy: Always