apiVersion: v1
kind: ConfigMap
metadata:
  name: godel-binder-config
  namespace: godel-system
data:
  godel-binder-config: |+
    apiVersion: godelbinder.config.kubewharf.io/v1beta1
    kind: GodelBinderConfiguration
    profile:
      plugins:
        victimChecking:
          pluginCollections:
            - plugins:
                - name: PDBChecker
              enableQuickPass: false
